### ISSUE TITLE
base value map keys vs. additional critical map entry

### ISSUE THREAD

**Issue by cabo** [cbor-wg/time-tag#8]
Section 3 says »The map must contain exactly one unsigned integer key, which specifies the "base time"«.  This is true for base time keys such as 1, 4, 5.  However, 10 and 11 are critical map entries that are in addition to a base time key.

So map keys for critical entries should be unsigned numbers.
Some of the critical map keys are base times, some are additional entries.
The definition of the map key must say which.
There is no problem with consuming critical entries without knowing which it is as all keys for critical entries must be known.

Should "base time" be a column in the IANA registry, too?

**Comment by chrysn** [comment]
I support splitting criticality from being "a base time" and allowing multiple of the former.

A column entry sounds like a practical thing to do; statements that "there is at most one base time", "base times need to be citical" and "documents establishing critical options must say whether they're a base time" would suffice as well.

**Comment by chrysn** [comment]
Good to see this resolved after a long time of not reading an updated document.

What I don't fully understand (maybe due to having lost context) is why -10 and -11 have a critical form. I maintain support for having non-basetime critical entries, but what could possibly be in key 10 that alters the time stamp's meaning to the extent that ignoring it produces a different value? (A timestamp of 1690199826 still refers to the point in time when I wrote this, no matter whether [America/Los_Angeles][u-ca=hebrew] applies to it or not, that seems to me to be inherently add-on information).

Do we have better examples? Best on my mind would be an "affine-transform" offset, where a value of [k, d] means that the number y given in base-time maps to the value x on the indicated timescale through y = k x + d. (So for example, a device using an internal 1024Hz clock could report its internal 32bit time stamp along with the offset stored last time it did something NTPish).

Also, was the idea of having "base time" be a column in the registry dropped? (AIU right now the difference between a base-time and any other critical entry is the presence of the string "Base Time" in the "Semantics" column).

**Comment by cabo** [comment]
-10 and -11 have a critical form because IXDTF (SEDATE) has a critical form.
Can't really do a "proof by lack of imagination" for a registry :-)

I don't have a strong opinion whether a column in the registry for base time is better than saying "Base Time" or "critical" in the semantics.  If you do, we could make this change.

**Comment by chrysn** [comment]
That's a fine explanation that'd have helped me. I like to hope I'd have understood that right away if there was a hint in the text; attempts to come up with a good proposal fell short as they all would have referred to the critical flag of sedate-datetime-extended, but this document generally just takes the meat out of there (eg. IXDTFtz) and does not translate to the full form.

Might it make sense to set one of the two items in the example to critical, with a corresponding ! flag in the approximate translation and the diagnostic comment?

As for the column, no strong opinion here either, just wanted to make sure it's not something that was lost.
